FROM maven:3.9.12-eclipse-temurin-11-alpine as build
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=build /build/target/*.jar  app.jar
EXPOSE 8080